home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
]

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('admin/', admin.site.urls),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('sss/', views.faq, name='faq'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm

from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'country']


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Cancelled', 'Cancelled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.crypto import get_random_string

from home.models import UserProfile
from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Product, Category


def index(request):
    return HttpResponse("Order App")


@login_required(login_url='/login')  # Check login
def addtocart(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user
    # Sepette eklenen üründen var mı kontrolü
    checkproduct = ShopCart.objects.filter(product_id=id)
    if checkproduct:
        control = 1
    else:
        control = 0

    if request.method == 'POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control == 1:
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
            request.session['cart_items'] = ShopCart.objects.filter(
                user_id=current_user.id).count()  # shopcartta ürün saydırma
            messages.success(request, "Ürün başarı ile sepete eklendi. ")
            return HttpResponseRedirect(url)

    else:
        if control == 1:
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()
        request.session['cart_items'] = ShopCart.objects.filter(
            user_id=current_user.id).count()  # shopcartta ürün saydırma
        messages.success(request, "Ürün başarı ile sepete eklendi. ")
        return HttpResponseRedirect(url)

    messages.warning(request, "Sepete eklemede hata oluştu.")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def shopcart(request):
    category = Category.objects.all()
    current_user = request.user
    schopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    total = 0
    for rs in schopcart:
        total += rs.product.price * rs.quantity

    context = {'schopcart': schopcart,
               'category': category,
               'total': total,
               }
    return render(request, 'shopcart_products.html', context)


@login_required(login_url='/login')
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    current_user = request.user
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    messages.success(request, "Ürün sepetten silindi.")
    return HttpResponseRedirect("/shopcart")


@login_required(login_url='/login')
def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    schopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in schopcart:
        total += rs.product.price * rs.quantity

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            schopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in schopcart:
                detail = OrderProduct()
                detail.order_id = data.id
                detail.product_id = rs.product.id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()

                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()

            ShopCart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_items'] = 0
            messages.success(request, "Siparişiniz başarı ile tamamlandı, teşekkürler")
            return render(request, 'order_completed.html', {'ordercode': ordercode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'schopcart': schopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               }
    return render(request, 'order_form.html', context)

order/templates/order_completed.html
{%  extends "homebase.html" %}

{% block title %}
    Sipariş
{% endblock %}

{% block keywords %}
{{ categorydata.keywords}}
{% endblock %}
{% block description %}
{{ categorydata.description }}
{% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}">
{% endblock %}



{% block content %}
	<hr class="soften">
	<div>
        <ul class="breadcrumb">
		    <li><a href="/">Anasayfa</a> <span class="divider">/</span></li>
		    <li class="active">Sipariş</li>
        </ul>
	</div>
	<hr class="soften">
	<div  class="row">
        Sevgili {{ user.first_name }} {{ user.last_name }}<br>
        Siparişiniz tamamlandı.<br>
        Sipariş Kodunuz: {{ ordercode }}<br>
        Yine bekleriz.



    </div>



{% endblock %}

order/templates/order_form.html
{%  extends "homebase.html" %}

{% block title %}
    Sipariş
{% endblock %}

{% block keywords %}
{{ categorydata.keywords}}
{% endblock %}
{% block description %}
{{ categorydata.description }}
{% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}">
{% endblock %}



{% block content %}
	<hr class="soften">
	<div>
        <ul class="breadcrumb">
		    <li><a href="/">Anasayfa</a> <span class="divider">/</span></li>
		    <li class="active">Sipariş</li>
        </ul>
	</div>
	<hr class="soften">
	<div  class="row">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="span6">
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                            <p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">Istanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">Izmir</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Konya">Konya</option>
                                    <option value="Yozgat">Yozgat</option>
                                </select></p>
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                            <div class="pull-right">
                                <button  type="submit" class="shopBtn btn-large">Siparişi Tamamla</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Payment Information</h4>
                            </div>
                            <p><label for="id_first_name">Total: </label>
                                <input type="text" name="total" class="input" readonly value="${{ total }}"></p>
                            <p><label for="id_first_name">Credit Card Holder</label>
                                <input type="text" name="holder" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Card Number</label>
                                <input type="text" name="number" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Security Number</label>
                                <input type="text" name="secnumber" class="input"  value=""></p>
                        </div>
                    </div>
                </div>

                </form>

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Shopcart Product List</h3>
                        </div>
                        <table class="table table-bordered table-condensed">
                            <thead>
                <tr>
                  <th>Ürün</th>
                  <th></th>
                  <th>Fiyat</th>
				  <th>Adet</th>
                  <th>Toplam</th>
                  <th></th>
				</tr>
              </thead>
              <tbody>
              {% for rs in schopcart %}
                <tr>
                  <td><img width="100" src="{{ rs.product.image.url}}" alt=""></td>
                  <td>{{ rs.product }}</td>
                  <td>${{ rs.product.price }}</td>
                  <td>{{rs.quantity}}</td>
                  <td>{{rs.amount}}</td>
                  <td>
				</td>
                </tr>
              {% endfor %}
                <tr>
                  <td colspan="6" class="alignR">Total products:	</td>
                  <td class="label label-primary"> ${{ total }}</td>
                </tr>
				</tbody>
            </table><br/>

                    </div>

                </div>


            </div>



{% endblock %}

order/templates/shopcart_products.html
{%  extends "homebase.html" %}

{% block title %}
    Shop Cart
{% endblock %}

{% block keywords %}
{{ categorydata.keywords}}
{% endblock %}
{% block description %}
{{ categorydata.description }}
{% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}">
{% endblock %}



{% block content %}
	<hr class="soften">
	<div>
        <ul class="breadcrumb">
		    <li><a href="/">Anasayfa</a> <span class="divider">/</span></li>
		    <li class="active">Shop Cart</li>
        </ul>
	</div>
	<hr class="soften">
	<div class="row">
	<div class="well well-small">
		<h1>Check Out </h1>
	<hr class="soften"/>

	<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>Ürün</th>
                  <th></th>
                  <th>Fiyat</th>
				  <th>Adet</th>
                  <th>Toplam</th>
                  <th></th>
				</tr>
              </thead>
              <tbody>
              {% for rs in schopcart %}
                <tr>
                  <td><img width="100" src="{{ rs.product.image.url}}" alt=""></td>
                  <td><a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}"> {{ rs.product.title }}</a></td>
                  <td>${{ rs.product.price }}</td>
                  <td>{{rs.quantity}}</td>
                  <td>{{rs.amount}}</td>
                  <td>
				  <div class="input-append">
					<a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Silmek istediğinize emin misiniz?')"> <button class="btn btn-mini btn-danger" type="button"><span class="icon-remove"></span></button></a>
				</div>
				</td>
                </tr>
              {% endfor %}
                <tr>
                  <td colspan="6" class="alignR">Total products:	</td>
                  <td class="label label-primary"> ${{ total }}</td>
                </tr>
				</tbody>
            </table><br/>



	<a href="/" class="shopBtn btn-large"><span class="icon-arrow-left"></span> Continue Shopping </a>
	<a href="/order/orderproduct" class="shopBtn btn-large pull-right">Next <span class="icon-arrow-right"></span></a>

</div>
</div>



{% endblock %}